### ISSUE TITLE
Combobox with search support for field names and operators

### ISSUE THREAD

**Issue by stefan-lacatus** [ptc-iot-sharing/QueryBuilderWidgetTWX#35]
## Problem description

Currently when creating a query, if multiple (>10) field names exist, it's hard for the user to identify them from the given dropdown.
Nowadays, users are used to having dropdowns with search options, so they can quickly type up the first characters of the option and see a realtime filter.

## Proposal

It seems that the upstream library that we are using, _jQuery QueryBuilder_ does have a plugin that replaces ALL `<select>` elements with _bootstrap-select_ that seems to offer a [Live Search](https://developer.snapappointments.com/bootstrap-select/examples/#live-search) functionality.
Alternatively, the same functionality also seems to be exposed by the [Chosen](https://querybuilder.js.org/plugins.html#chosen-selectpicker) plugin.

The library that will be used is going to be: `// todo`

The goal of this task would be to add a new design time property, `useComboBoxes` (defaults to `false`). When enabled, the functionality described above is activated.

## Task list

- [ ] Create a local development environment
- [ ] Add design time property
- [ ] Figure out how to activate the plugin. Preferably, use the npm distribution https://www.npmjs.com/package/bootstrap-select or https://www.npmjs.com/package/chosen-js
- [ ] Have this enabled only when `useComboBoxes` is set to true.
- [ ] Optional. Don't load the `boostrap-select` plugin and the js/css files when is set to false.

**Comment by stefan-lacatus** [comment]
@OvidiuAndrei98: see above
